In [1]:

import pandas as pd
import time
from datetime import datetime, timedelta
import pipeline_fct


# File path
compute_situation_path = 'Data/4_computed_as/all_trades_compute_situation.csv'
enriched_situation_path = 'Data/3_enriched_as/all_trades_enriched_as.csv'
# enriched_situation_path = 'Data/3_enriched_as/3_test.csv'
account_situation_path = 'Data/2_account_situation/all_trades_account_situation.csv'

In [17]:
asdf_currency_used = pipeline_fct.get_currency_list_from_asdf(account_situation_path)

enriched_situation = pd.read_csv(enriched_situation_path, sep=',')

col_to_keep = ['Date','EUR','ETH','BTC','SEI','QNT','ETH_price','BTC_price','SEI_price','QNT_price']
computed_situation = enriched_situation[col_to_keep].copy(deep=True)

computed_situation.head()

,Date,EUR,ETH,BTC,SEI,QNT,ETH_price,BTC_price,SEI_price,QNT_price
0,2023-04-23 14:22:33,-242.35,0.14000,0.000000e+00,0.0,0.0,1697.390632,25159.742118,NaN,103.069332
1,2023-04-23 14:24:00,-496.86,0.14000,1.000000e-02,0.0,0.0,1697.390632,25159.742118,NaN,103.069332
2,2023-05-10 19:53:47,-496.86,0.28664,1.100000e-07,0.0,0.0,1684.884394,25223.868164,NaN,96.736584
3,2023-05-17 15:01:12,-32.94,0.00000,1.100000e-07,0.0,0.0,1667.084925,24845.066096,NaN,96.789091
4,2023-05-19 13:56:51,-33.85,0.00000,3.591000e-05,0.0,0.0,1677.434135,24898.730492,NaN,96.072881

In [20]:
col_to_compute = ['ETH','BTC','SEI','QNT']
for currency in col_to_compute :
    currency_amount_eur_column = f"{currency}_amount_eur"
    currency_price_column = f"{currency}_price"
    computed_situation[currency_amount_eur_column] = computed_situation[currency]*computed_situation[currency_price_column]
computed_situation.head()

,Date,EUR,ETH,BTC,SEI,QNT,ETH_price,BTC_price,SEI_price,QNT_price,ETH_amount_eur,BTC_amount_eur,SEI_amount_eur,QNT_amount_eur
0,2023-04-23 14:22:33,-242.35,0.14000,0.000000e+00,0.0,0.0,1697.390632,25159.742118,NaN,103.069332,237.634688,0.000000,NaN,0.0
1,2023-04-23 14:24:00,-496.86,0.14000,1.000000e-02,0.0,0.0,1697.390632,25159.742118,NaN,103.069332,237.634688,251.597421,NaN,0.0
2,2023-05-10 19:53:47,-496.86,0.28664,1.100000e-07,0.0,0.0,1684.884394,25223.868164,NaN,96.736584,482.955263,0.002775,NaN,0.0
3,2023-05-17 15:01:12,-32.94,0.00000,1.100000e-07,0.0,0.0,1667.084925,24845.066096,NaN,96.789091,0.000000,0.002733,NaN,0.0
4,2023-05-19 13:56:51,-33.85,0.00000,3.591000e-05,0.0,0.0,1677.434135,24898.730492,NaN,96.072881,0.000000,0.894113,NaN,0.0

In [ ]:


    computed_situation["total_eur"] = 0  # Initialise la colonne de somme à zéro
    for currency in asdf_currency_used :
        currency_amount_eur_column = f"{currency}_amount_eur"
        computed_situation["total_eur"] += computed_situation[currency_amount_eur_column] 
    
    computed_situation.to_csv(compute_situation_path, index=False)